### ISSUE TITLE
Roadmap para estudos

### ISSUE THREAD

**Issue by thaymara** [training-center/frontend-study-group#4]
Olá pessoal!
No channel do slack (#frontend-studies) surgiu a discussão sobre criar um roadmap para o grupo e o Paulo Ilarde começou a criar um e agora estamos passando a discussão para o git para podermos ter a opinião de todos antes de subir pro git
Sintam-se à vontade para mudar a ordem, acrescentar/ retirar coisas :)

## **Básico**

**_HTML:_** 
- O que é HTML?
- Estrutura básica de um site
- Doctype, tag html, tag head, tag body
- Títulos, parágrafos, listas, imagens, forms

**_CSS:_**

- O que é CSS?
- CSS inline, interno e externo
- seletores CSS: classe, id e elemento
- propriedades da fonte: cor, estilo, capitalização
- background da página/ seção

**_JS:_**

- O que é JS?
- JS != Java ;
- script interno e externo;
- variáveis
- operadores (lógicos e aritméticos)
- condicionais
- loops/ laços de repetição
- funções

## **Intermediário**

**_HTML:_**

- saber usar as tags anteriores sem necessidade de consulta
- tags depreciadas
- tags sem fechamento

**_CSS:_**

- bordas, margin e padding
- pseudo classes e elementos
- responsividade (media queries)
- transition/ transform
- position (absolute, relative)
- arquivos de fonte
- box model
- arquitetura de CSS (boas práticas)

**_JS:_**

- Objetos
- Arrays
- closures
- automatizador de tarefa (gulp, grunt)

## **Avançado**

**_HTML:_**

- acessibilidade
- validação de forms (validar os campos apenas)
- meta tags
- APIs
- DOM

**_CSS:_**

- flexbox
- CSS Grid
- Frameworks/ libs (foundation, bulma, bootstrap)
- pre compilador/ processador (sass, less)

**_JS:_**

- ES6
- Frameworks/ libs (jQuery, angular, react, vue)

**Comment by AlexsandroSA** [comment]
Acho interessante incluir desafios/projetos para fixar mais o conteúdo.

Obs.: O roadmap ficou bem legal ;)

**Comment by iagolaguna** [comment]
Ontem quando conclui meus estudos estava pensando se haveria algum roadmap de estudos mas no caso  oque eu imaginei

Vários templates de sites (desafios) do basico ao avançado aonde com o grau de dificuldade os templates iriam ficando mais ricos em informações gradativamente, e conforme o conteudo muda se criaria alguns criteiros de aceites, exemplo:
 * "Faça x requisiçã ajax" usando async/await.
 * Faça o footer do site utilizando flex-box.
 * Utilize as novas tags do html5.


Assim por diante, estou a disposição para ajudar com oque eu puder sobre o projeto.

**Comment by pauloilarde** [comment]
Eu acho interessante sim criarmos alguns desafios semelhante ao que o freeCodeCamp faz (crie uma página de tributo, uma página pessoal) de acordo com o nível.
Eu particularmente tenho certa dificuldade em criar algo kkkk

**Comment by ghost** [comment]
Acho interessante pontuar em qual nível fica **saber layoutar**. No mais ta bem interessante, vou começar a analisar meu conhecimento por aí.

**Comment by Raffesmind** [comment]
Uma coisa interessante que podemos colocar em vez de ser apenas um RoadMap de estudos, poderia ser um RoadMap de Skill esperadas.

Lendo novamente o que foi levantado, tenho algumas sugestões para adicionar de conteúdo a ser discutido: 

Básico: 
HTML - Uso de Blockquote, tipos de tag inline/block, tabelas 
CSS - Alterando fontes, cores/background, bordas, espaçamento
JS - Objetos

Intermediário
HTML - Forms, Inputs, legends; Video; Picture; Iframe e semântica do código;
CSS - Imagens internas, Media-Query X Responsividade 
JS - Const e Let, destructuring, modulos, ES6, entendendo interação navegador X javascript

Avançado:
HTML - SVG, Canvas
CSS - Fill, :root, diferentes níveis de CSS, CSS modular, variaveis;
JS - Frameworks, eventos

E @Jitors acho que Layoutar vai dependendo muito do objetivo do grupo, pois acho que isso é uma habilidade que tanto pode não ser objetivo do grupo, dado uma grande complexidade na parte de engenharia para codificar tudo, como também, pode ser importante para saber mais processos e interação com o usuário, precisando ser necessário analisar o que é layoutar ou apenas se virar em questão de bibliotecas ou ferramentas hoje. 

No mais, boa iniciativa @thaymara por ter postado aqui :) E @pauloilarde por ter iniciado a discussão no TC.

**Comment by ghost** [comment]
@Raffesmind Achei a ideia bem interessante, ficaria mais fácil gerir as habilidades de conhecimento. Sobre o layout, eu falava sobre layoutar paginas com HTML e CSS(sem ajuda de frameworks), pois, creio eu, que seja uma habilidade imprescindível para quem quer ser front-end.

**Comment by Raffesmind** [comment]
@Jitors acho que eu não entendi a pergunta então hahaha 
Desculpa, pode me explicar mais um pouco qual é a ideia e um exemplo talvez prático disso? 
Porque eu ainda estou entendendo muito como uma construção de Design e não necessariamente de código e queria entender melhor até para trabalhamos isso no plano de estudos :)

**Comment by ghost** [comment]
@Raffesmind Eu falo de tipo saber estruturar o layout desenhado no photoshop para html e css, sem quebrar o layout.

**Comment by adrianoavelino** [comment]
Legal a ideia dos desafios desde que não precise criar algo completo no básico. No básico acredito que seria interessante realizar as partes (componentes) de um layout e ir evoluindo para o intermediário e avançado e juntar os elementos. Dessa forma o estudante consegue ver resultados e acompanhar a sua evolução. Quem sabe adicionar dicas para cada desafio para ajudar o processo de resolução do estudante. Sei lá, só estou coletando ideias!  ;D

**Comment by Raffesmind** [comment]
@Jitors entendi a questão agora! 
Acho que isso pode ser feito através de exercícios e práticas, porque em teoria, as coisas já estão contempladas, só devemos saber como colocar em prática para ficar cada vez mais fácil :) 

@adrianoavelino eu gosto bastante da ideia, acho que poderiamos criar uma outra Issue/Thread para discutir possibilidade de projetos e ordem, colocar coisas palpáveis de desafios, como o pessoa do javascript-studies fez! 

Uma coisa que eu tava vendo e pode ser importante colocar em intermediário ou talvez avançado nessa ordem é trabalhar com APIs, fazer fetch/ajax com JSON e como ir trabalhando isso dentro do JS, o que acham?

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda é relevante manter aberto?

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by thaymara** [comment]
Eu acredito que daria pra fechar, a não ser que mais alguém queira dar continuidade no roadmap

**Comment by Diego-Brocanelli** [comment]
Por mim sem problema permanecer em aberto, porém atualmente essa issue encontra-se parada, e assim não vejo vantagem em manter aberto tanto tempo sem movimentação.

**Comment by thaymara** [comment]
Sim, concordo, eu acho que pode fechar então, não acredito que vá ter uma nova movimentação tão cedo assim :)

**Comment by Diego-Brocanelli** [comment]
Obrigado pelo retorno @thaymara .
